# Secrets pour Streamlit Cloud
# NE PAS COMMITTER CE FICHIER !

[default]
FMP_API_KEY = "Xqz3Plda2PdzuAZysmLeR1qL4dsFAcwd"
ANTHROPIC_API_KEY = "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"
NEWSAPI_KEY = "1b65ce75e09a404d9637be2406dce451"
FRED_API_KEY = "6d2eaf9480daccd484401a8d6728f4ad"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "haasm26@gmail.com"
SMTP_PASSWORD = "jgvj bbxh xspa pvwk"

REDIS_URL = "redis://localhost:6379"